### ISSUE TITLE
tables.exception

### ISSUE THREAD

**Issue by parulj3795** [danielemichilli/SpS#1]
Hello,

I'm trying to install SpS-searcher on Ubuntu-18.04 machine. I'm getting the following error

$ python2 sps.py file.singlepulse 
Traceback (most recent call last):
  File "sps.py", line 6, in <module>
    from src import SPclean
  File "/home/parul/WORK/RB/SpS-master/sps/src/SPclean.py", line 11, in <module>
    from tables.exceptions import HDF5ExtError
ImportError: No module named tables.exceptions

I've repeatedly tried to install tables and HDF5. It doesn't seem to work.

**Comment by danielemichilli** [comment]
You need to install tables. E.g. https://stackoverflow.com/questions/25980018/importerror-hdfstore-requires-pytables-no-module-named-tables
